Revert "This should not be necessary and fails with PHPUnit <3.5.0."
This reverts commit 11178154ce626fbf64d1a533ac5dd42028af66bb.

This is necessary - or else I get:
Fatal error: Class 'PHPUnit_TextUI_TestRunner' not found[...]